config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'persons/profile'
  root 'menus#index'

  #get 'users/sign_out', to: root_path
  get 'persons/profile', as: 'user_root'

  get '/update_level', to: 'levels#update_level'
  post '/run_program', to: 'levels#run_program'

  get '/run_line', to: 'levels#run_line'

  resources :levels
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/level.rb
class Level < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  #def after_sign_in_path_for(resource)
  #  current_user_path
  #end

  #def after_sign_out_path_for(resource_or_scope)
    #request.referrer
  #end

end

app/controllers/levels_controller.rb
require 'json'

class LevelsController < ApplicationController

  @@id = 0

  $width = 0
  $height = 0
  $start = 0
  $end = 0
  $rotation = 0
  $labyrinth = []
  $blocks = []

  $code = []
  $is_run = false

  def index
    @level = Level.all
  end

  def levels

  end

  def update_values
    @level = Level.find(@@id)
    $width = @level.width
    $height = @level.height
    $start = @level.start
    $end = @level.end
    $rotation = @level.rotation
    $labyrinth = JSON.parse(@level.labyrinth)
    $blocks = JSON.parse(@level.blocks)
  end

  def find_new_position(position)
    if $rotation % 2 == 0
      if $rotation == 0
        position -= position / $width == 0 ? 0 : $width
      else
        position += position / $width == $height - 1 ? 0 : $width
      end
    else
      if $rotation == 1
        position += position % $width == $width - 1 ? 0 : 1
      else
        position -= position % $width == 0 ? 0 : 1
      end
    end
    position
  end

  def forward
    new_position = find_new_position($start)

    if $labyrinth.include? new_position
      if $blocks.include? new_position
        block_new_position = find_new_position(new_position)
        if block_new_position != new_position and $labyrinth.include? block_new_position
          block_index = $blocks.find_index new_position
          puts block_index
          $blocks[block_index] = block_new_position
          $start = new_position
        end
      else
         $start = new_position
      end
    end
  end

  def run_line
    up_line = $code[0]
    case up_line
    when 130..256 then #forward(...)
      forward
      $code[0] = $code[0] - 1
    when 129 then #forward
      forward
      $code = $code[1..$code.length-1]
    when 0 then #leftRotate
      $rotation = ($rotation + 3) % 4
      $code = $code[1..$code.length-1]
    when 1 then #rightRotate
      $rotation = ($rotation + 1) % 4
      $code = $code[1..$code.length-1]
    else
      $is_run = false
      $code = []
    end
    render json: up_line
  end

  def run_program
    unless $is_run
      $is_run = true
      $code = []
      update_values

      text_code = params[:code].split(/\r?\n/)
      mistake_index = 0
      i = 1
      text_code.each do |line|
        unless /^forward\(\d*\);$/.match?(line) or /^leftRotate\(\);$/.match?(line) or /^rightRotate\(\);$/.match?(line)
          mistake_index = i
          break
        end
        i += 1
      end
      if mistake_index == 0
        0.upto text_code.length - 1 do |j|
          line = text_code[j].match(/\((?<argument>.*)\);/)
          if line[:argument] == ""
            if text_code[j] == "leftRotate();"
              $code[j] = 0
            else
              if text_code[j] == "rightRotate();"
                $code[j] = 1
              else
                $code[j] = 129
              end
            end
          else
            $code[j] = 128 + line[:argument].to_i
          end
        end
      end
      render json: mistake_index
    end
  end

  def update_level
    #if $now_values == []
    #  update_values
    #end
    result = [$width, $height, $start, $end, $rotation, $labyrinth, $blocks]
    render json: result
  end

  def show
    @level = Level.find(params[:id])
    @@id = params[:id]
    update_values
  end

  def create
    @level = Level.new(level_params)
    @level.save
    redirect_to @level
  end

  private def level_params
    params.require(:level).permit(:width, :height, :start, :end, :rotation, :labyrinth, :blocks)
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  def index

  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/edit_levels_helper.rb
module EditLevelsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learning Algorithmization</title>
    <%= favicon_link_tag 'logo.ico' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="/" class="nav-link px-2 text-white">Home</a></li>
          <li><a href="/about" class="nav-link px-2 text-white">About</a></li>
        </ul>

        <div class="text-end">
          <% if user_signed_in? %>
            <span>Здравствуйте, <%= current_user.email %></span>
            <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete, :class => "btn btn-warning" %>
          <% else %>
            <%= link_to 'Sign In', new_user_session_path, :class => "btn btn-outline-light me-2"%>
            <%= link_to 'Sign Up', new_user_registration_path, :class => "btn btn-warning" %>
          <% end %>
        </div>
      </div>
    </div>
  </header>
    <%= yield %>
  </body>
</html>

app/views/levels/index.html.erb
Levels
<% @level.each do |level| %>
  <%= button_to level.id, level_path(level), method: :get%>
<% end %>

app/views/levels/level1.html.erb
<% @width = "512" %>
<% @height = "512" %>
<div data-controller="levels">
  <div class="header">Level 1</div>
  <div class="help"></div>
  <div class="code"><textarea id="code"></textarea><button id='run'>RUN</button></div>
  <div class="field"><canvas id="myCanvas" width=<%= @width %> height=<%= @height %>></canvas></div>
</div>

app/views/levels/new.html.erb
Add new Level

<%= form_for :level, url: levels_path do |f| %>
  <br>width <%= f.text_field(:width, {:class => 'form-control'}) %> </br>
  <br>height <%= f.text_field(:height, {:class => 'form-control'}) %> </br>
  <br>start <%= f.text_field(:start, {:class => 'form-control'}) %> </br>
  <br>end <%= f.text_field(:end, {:class => 'form-control'}) %> </br>
  <br>rotation <%= f.text_field(:rotation, {:class => 'form-control'}) %> </br>
  <br>labyrinth <%= f.text_field(:labyrinth, {:class => 'form-control'}) %> </br>
  <br>blocks <%= f.text_field(:blocks, {:class => 'form-control'}) %> </br>
  <%= f.submit("Add", {:class => 'btn btn-warning'}) %>
<% end %>

app/views/levels/show.html.erb
<% @width = "512" %>
<% @height = "512" %>
<div data-controller="levels">
  <div class="header">Level <%= @level.id %></div>
  <div class="help"></div>
  <div class="code"><textarea id="code"></textarea><button id='run'>RUN</button></div>
  <div class="field"><canvas id="myCanvas" width=<%= @width %> height=<%= @height %>></canvas></div>
</div>

app/views/menus/index.html.erb
<%= button_to 'Play', '/levels', method: :get %>
<%= button_to 'Add level', '/levels/new', method: :get %>

app/views/persons/profile.html.erb
<h1>Persons#profile</h1>
<p>Find me in app/views/persons/profile.html.erb</p>